{% set name = "molfeat" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/molfeat-{{ version }}.tar.gz
  sha256: d033b93bdd025d7e9f0aeec0be038d1a21c76ef6b538d2ce2380d06f45b05bb2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - tqdm
    - pyyaml
    - loguru
    - joblib
    - filelock
    - fsspec
    - s3fs
    - gcsfs
    - platformdirs
    - python-dotenv

    # Scientific
    - pandas
    - numpy
    - scipy
    - h5py
    - pyarrow
    - matplotlib-base
    - pydantic >=2.0.0

    # Chemistry
    - datamol >=0.8.0
    - rdkit >=2021.09
    - pmapper
    - mordred

    # ML
    - pytorch >=1.12
    - scikit-learn

test:
  imports:
    - molfeat
  # requires:
  #   - pytest
  # source_files:
  #   - tests/
  # commands:
  #   - pytest --verbose tests/

about:
  home: https://github.com/datamol-io/molfeat
  summary: A python library to featurize molecules.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cwognum
    - hadim
    - maclandrol
